name = "TrixiBase"
uuid = "9a0f1c46-06d5-4909-a5a3-ce25d3fa3284"
authors = ["Michael Schlottke-Lakemper <michael@sloede.com>"]
version = "0.1.3-pre"

[weakdeps]
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"

[extensions]
TrixiBaseMPIExt = "MPI"

[compat]
MPI = "0.20"
julia = "1.8"

[extras]
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
