name = "TrixiBase"
uuid = "9a0f1c46-06d5-4909-a5a3-ce25d3fa3284"
authors = ["Michael Schlottke-Lakemper <michael@sloede.com>"]
version = "0.1.6"

[deps]
ChangePrecision = "3cb15238-376d-56a3-8042-d33272777c9a"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[weakdeps]
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"

[extensions]
TrixiBaseMPIExt = "MPI"

[compat]
ChangePrecision = "1.1.0"
MPI = "0.20"
TimerOutputs = "0.5.25"
julia = "1.10"

[extras]
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
